### ISSUE TITLE
Missing lists when adding emails

### ISSUE THREAD

**Issue by tstizzle** [phpList/phplist-ui-bootlist#35]
I saw this was reported a while ago, but i am unable to get it working, even after the commits you have made of late.  when adding emails via copy & paste, the Lists dialog is hidden by default.  this is the div: "**<div role="tabpanel" class="@ tab-pane fade" id="importlists1"><ul class="list-unstyled">**".

i know this was reported as a bug on mobile at the beginning of this year, but i get it on FF, chrome and safari on mac.

**Comment by mariez** [comment]
Hi tstizzle! Can you add a screenshot of what you see?

**Comment by tstizzle** [comment]
attached.  the lists are hidden on all upload methods in Subscribers->Import Emails.  i have highlighted the active lists in dev tools so you can see they are present.

confirmed on FF 48.0.2, chrome 490.0.2623.112, FF 56.0.2, chrome 62.0.3202.94.

![phplist](https://user-images.githubusercontent.com/11138825/32852571-328c4d3a-c9ed-11e7-876d-e2e148fdf3c3.jpg)

**Comment by tstizzle** [comment]
btw, thanks for taking a look at this @mariez !

**Comment by mariez** [comment]
@tstizzle thanks for this information. Just one more question: This happens in that browsers only on this import by copy/paste screeen? Or in other  2 import emails screens too ("import by uploading a file" and "import by uploading a csv file"?

**Comment by tstizzle** [comment]
hi, it happens in all 3 import screens, on all browsers.

**Comment by mariez** [comment]
Thanks.

**Comment by mariez** [comment]
@tstizzle I checked on Chome 62 and FF56 and it is working for me. Then I took a better look to your image, and the code  in your screenshot has the old bug that was resolved in this commit:
https://github.com/phpList/phplist-ui-bootlist/commit/282341f2e01f7809d66b27445b984e700ec477d9
If you take a look at the file  js/phpList3ToBootstrap.js in that commit, the javascript that wrap the checkbox inside a "<div class="checkbox checkbox-inline"> was commented, so that should not happen anymore, but in your screenshot the checkboxes are wraped insde a div with the classes "checkbox checkbox-inline".
So i think your theme is using and old version of this js files. You can check this opening the file 
/lists/admin/ui/phplist-ui-bootlist/js/dist/phpList_ui_bootlist.min.js  and search the word "checkbox-inline". If you find it, it is an old version. You can download the last version of the Trevelin theme from this repository.

**Comment by tstizzle** [comment]
hi @mariez  , thanks for catching that.   it looks like we must have bad timing, and snuck inside a release window: after phpList 3.3.1 (feb 12) but before commit 282341f (mar 31).  my bad.  i was certain the commit came before the release of v3.3.1.  i'm assuming this fix is now in 3.3.1 and future upgrades?

i will make sure to post back here with results after i get the js file.  thanks again.  sorry to waste your time!

**Comment by mariez** [comment]
Help you never can be a waste of time :) 
I don't know much about releases, but i am sure @samtuke  can answer your last question.

**Comment by tstizzle** [comment]
fixed me right up.  thanks again @mariez !
